# Site settings
title: Gaussian Process Round Table
author:
  name: Neil D. Lawrence
  email: 
description: > # this means to ignore newlines until "baseurl:"
  The Gaussian Process Round Table was the first in a series of meetings around Gaussian processes.
baseurl: "/gprt" # the subpath of your site, e.g. /blog/
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss

url: https://gpss.cc # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  gpschool
facebook_page: gaussianprocesssummerschool

ghub:
  edit: true
  repository: gprt

conference:
  logo: gpss-logo.svg
  name: Gaussian Process Round Table
  short_name: GPRT
  full_name: Gaussian Process Round Table
  location: Sheffield, UK
  venue: The University of Sheffield
  dates:
  - 2005-06-09
  - 2005-06-10
  chairs:
  - type: Organizer
    people:
    - family: Lawrence
      given: Neil D.
      institute: The University of Sheffield
      url: https://inverseprobability.com
  sponsors:
  - name: PASCAL Network of Excellence
    url: https://www.k4all.org/project/25/
  - name: Machine Learning Group, University of Sheffield
    url: https://www.dcs.shef.ac.uk/ml
analytics:
  google:
    tracking_id: UA-62991754-1
# Build settings
markdown: kramdown
