# Site settings
title: Gaussian Process Round Table
author:
  name: Neil Lawrence
  email: 
description: > # this means to ignore newlines until "baseurl:"
  The Gaussian Process Round Table was the first in a series of meetings around Gaussian processes.
baseurl: "/gprt/" # the subpath of your site, e.g. /blog/
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings

logo: "gpss_logo.svg"
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

ghub:
  edit: true
  repository: gprt


analytics:
  google:
    tracking_id: UA-62991754-1
# Build settings
markdown: kramdown
